config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :words
  
  
  devise_for :users
  
  get "users", to: "devise/session#new"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  #scope :search, ->(key) {User.where("words LIKE ?","%"+key+"%")}      
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :user

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  


  
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, expect: [:show, :index]

  # GET /words or /words.json
  def index
    @words = Word.all
  end

  # GET /words/1 or /words/1.json
  def show
  end

  # GET /words/new
  def new
    @word = Word.new
  end

  # GET /words/1/edit
  def edit
  end

  # POST /words or /words.json
  def create
    @word = Word.new(word_params)
    @word.user = current_user
    respond_to do |format|
      if @word.save
        format.html { redirect_to word_url(@word), notice: "Word was successfully created." }
        format.json { render :show, status: :created, location: @word }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /words/1 or /words/1.json
  def update
    respond_to do |format|
      if @word.update(word_params)
        format.html { redirect_to word_url(@word), notice: "Word was successfully updated." }
        format.json { render :show, status: :ok, location: @word }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1 or /words/1.json
  def destroy
    @word.destroy

    respond_to do |format|
      format.html { redirect_to words_url, notice: "Word was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def word_params
      params.require(:word).permit(:word, :meaning)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-dark bg-info">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" >DICTIONARY</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      <ul class="nav navbar-nav navbar-right">
       
        <% if user_signed_in? %>
          <li><a href="/">HOME</a></li>
           <li><a href="/words">WORDS</a></li>
          <li><a href="/users/edit">EDIT PROFILE</a></li>
          <li><%= button_to "LOG OUT",destroy_user_session_path, method: :delete%></li>
        <% else%>
          <li><a href="/">HOME</a></li>
           
          <li><a href="/users/sign_up">SIGNUP</a></li>
          <li><a href="/users/sign_in">LOGIN</a></li>
        <% end%>
           
      </ul>
    </li>
    </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/home/index.html.erb
<h1>DICTIONARY</h1>


<%= link_to "WORDS", words_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dictionary</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'home/header' %>
    <div class="container">
    <%= yield %>
    
  </body>
    
</html>

app/views/words/_form.html.erb
<%= form_with(model: word) do |form| %>
  <% if word.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
        <% word.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :word, style: "display: block" %>
    <%= form.text_field :word %>
  </div>

  <div>
    <%= form.label :meaning, style: "display: block" %>
    <%= form.text_area :meaning %>
  </div>

  <div>
    <%= form.label :favourite_word, style: "display: block" %>
    <%= form.text_field :word %>
  </div>

  

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/words/_word.html.erb
<div id="<%= dom_id word %>">
  <p>
    <strong>Word:</strong>
    <%= word.word %>
  </p>

  <p>
    <strong>Meaning:</strong>
    <%= word.meaning %>
  </p>
  
  <p>
    <strong>favourite_word(yes/no):</strong>
    <%= word.favourite %>
  </p>

  

</div>

app/views/words/edit.html.erb
<h1>Editing word</h1>

<%= render "form", word: @word %>

<br>

<div>
  <%= link_to "Show this word", @word %> |
  <%= link_to "Back to words", words_path %>
</div>

app/views/words/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Words</h1>

<div id="words">
  <% @words.each do |word| %>
    <%= render word %>
    <% if current_user && current_user.admin %>
          <%= link_to "WORDS", words_path %>
          <%= link_to "New word", new_word_path %>
          <p>
            <%= link_to "Show this word", word %>
          </p>
        <% else%>
          <p>
            <%= link_to "Show this word", word %>
          </p>
        <% end%>
   
  <% end %>
</div>

app/views/words/new.html.erb
<h1>New word</h1>

<%= render "form", word: @word %>

<br>

<div>
  <%= link_to "Back to words", words_path %>
</div>

app/views/words/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @word %>

<div>
    <% if current_user && current_user.admin %>
       <%= link_to "Edit this word", edit_word_path(@word) %> |
       <%= link_to "Back to words", words_path %>

        <%= button_to "Destroy this word", @word, method: :delete %>
      
    <% else%>
         <%= link_to "Back to words", words_path %>
    <% end%>
   
  
</div>